# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###


POST 127.0.0.1:8000/api/update-profile
Content-Type: application/json

{
  "FullName": "string",
  "UsfEmail": "string",
  "PreferredStudyTime": "morning",
  "Classes": {
    "Calculus": 2,
    "Chemistry": 0
  }
}